apiVersion: cluster.k8s.io/v1alpha1
kind: MachineSet
metadata:
  name: master
spec:
  replicas: 1
  template:
    metadata:
    spec:
      providerConfig:
        value:
          apiVersion: kubeadm.playground/v1alpha1
          kind: KubeadmPlaygroundMachineSet
          box: "ubuntu/xenial64"
          cpus: 2
          memory: 2048
      roles:
        - Master
