apiVersion: cluster.k8s.io/v1alpha1
kind: MachineSet
metadata: 
  name: node
spec: 
  replicas: 1
  template: 
    metadata: 
    spec: 
      providerConfig: 
        value: 
          apiVersion: vagrantproviderconfig/v1alpha1
          kind: VagrantProviderConfig
          box: "ubuntu/xenial64"
          cpus: 2
          memory: 2048
      roles: 
        - Node
